## Author

- **Name:** Botao Huang  
- **Email:** botaoh3@illinois.edu

## Purpose

This shiny App aims to provide a visualization of Covid-19 data separated by specific time periods as well as the regions. Users are able to select the state they want (US or states), the Year they want, and the month they want. After these procedures, they will be able to see a histogram based on that monthly data. In the table panel, users will find the general information about the data in general which automatically updates according to the selections they make previously in the first tab panel. 



## Data

The data set includes Covid-19 related information from 2020-01 to 2022-11, some of the most important information used in this data set are: the Year in which deaths occurred, Month in which deaths occurred, the jurisdiction of occurrence, sex groups, Age Group, and Covid-19 deaths. This data set is set to send a message about the distinction of deaths within sexes and age, and involves other relevant medical information like pneumonia and influenza. Since I downloaded this file in November, meaning the most updated information (e.g. 2022-12) is not included in this App. 



## References
National Center for Health Statistics (2020). Provisional COVID-19 Deaths by Sex and Age. https://data.cdc.gov/d/9bhg-hcku.

